---
- name: Add Jenkins repo
  get_url:
    url: {{ jenkins_repo }}
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import GPG key
  rpm_key:
    state: present
    key: {{ jenkins_repo_key }}

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start and Enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes