---
work_dir: "/var/www/html"
log_dir: "/var/log/httpd"
conf_dir: "/etc/httpd/conf.d"
db_root_pass: ""
testlink_db: "testlink"
testlink_user: "testlinkuser"
testlink_user_pass: "PassW0RDTESTLINK"
testlink_conf_file: "testlink.conf"