---
- name: Install EPEL repo (Amazon Linux)
  shell: "amazon-linux-extras install epel -y "
  when: ansible_distribution == 'Amazon'
  tags:
    - deploy

- name: Install EPEL repo (CentOS)
  yum:
    name: epel-release
  when: ansible_distribution == 'CentOS'
  tags:
    - deploy