---
- name: Yum Update
  shell: yum update -y

- name: Install Default Programs
  yum:
    name:
      - vim
      - tmux
      - tree
      - htop
      - wget
      - curl
      - bash-completion
      - git
      - nmap
      - tcpdump
      - net-tools
      - bind-utils
  tags:
    - deploy