---
- name: Install Apache Server
  yum:
    name:
      - httpd

- name: Disable Apache default welcome page
  shell: "sed -i 's/^/#&/g' /etc/httpd/conf.d/welcome.conf"

- name: Prevent Apache from listing web directory files to visitors
  shell: "sed -i 's/Options Indexes FollowSymLinks/Options FollowSymLinks/' /etc/httpd/conf/httpd.conf"

- name: Start and Enable Apache Server
  systemd:
    name: httpd
    state: started
    enabled: yes