---
- name: Install Webtatic repo
  shell: "rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"
  tags:
    - deploy

- name: Install PHP 5.6 and extensions
  yum:
    name:
      - php56w
      - php56w-mysqlnd
      - php56w-common
      - php56w-gd
      - php56w-ldap
      - php56w-cli
      - php56w-mcrypt
      - php56w-xml
    state: latest
  tags:
    - php56

- name: Install PHP 7 and extensions
  yum:
    name:
      - mod_php71w
      - php71w-mysqlnd
      - php71w-common
      - php71w-gd
      - php71w-ldap
      - php71w-cli
      - php71w-mcrypt
      - php71w-xml
    state: latest
  tags:
    - php71

- name: Modify PHP settings
  shell: |
    cp /etc/php.ini /etc/php.ini.bak
    sed -i 's/session.gc_maxlifetime = 1440/session.gc_maxlifetime = 2880/' /etc/php.ini
    sed -i 's/max_execution_time = 30/max_execution_time = 120/' /etc/php.ini
    exit 0
  tags:
    - deploy
