---
- name: Download the TestLink {{ testlink_version }} archive, unzip the archive to the {{ work_dir }} directory
  shell: |
    cd /tmp
    wget https://github.com/TestLinkOpenSourceTRMS/testlink-code/archive/{{ testlink_version }}.tar.gz
    tar -zxvf {{ testlink_version }}.tar.gz -C {{ work_dir }}
    chown -R apache:apache {{ work_dir }}/testlink-code-{{ testlink_version }}
    exit 0

- name: Create a custom configuration file for TestLink
  shell: cp {{ work_dir }}/testlink-code-{{ testlink_version }}/custom_config.inc.php.example {{ work_dir }}/testlink-code-{{ testlink_version }}/custom_config.inc.php

- name: Create Virtual Host for Testlink
  template:
    src: "templates/{{ testlink_conf_file }}.j2"
    dest: "{{ apache_conf_dir }}/{{ testlink_conf_file }}"

- name: Restart Apache
  systemd:
    name: httpd
    state: restarted