---
- name: Download the TestLink 1.9.16 archive, unzip the archive to the {{ work_dir }} directory
  shell: |
    cd /tmp
    wget https://github.com/TestLinkOpenSourceTRMS/testlink-code/archive/1.9.16.tar.gz
    tar -zxvf 1.9.16.tar.gz -C {{ work_dir }}
    chown -R apache:apache {{ work_dir }}/testlink-code-1.9.16
    exit 0

- name: Create a custom configuration file for TestLink
  shell: cp {{ work_dir }}/testlink-code-1.9.16/custom_config.inc.php.example {{ work_dir }}/testlink-code-1.9.16/custom_config.inc.php

- name: Create Virtual Host for Testlink
  template:
    src: "templates/{{ testlink_conf_file }}.j2"
    dest: "{{ conf_dir }}/{{ testlink_conf_file }}"

- name: Restart Apache
  systemd:
    name: httpd
    state: restarted