---
- name: Pre-install programs
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

#- name: Add Docker repo
#  yum_repository:
#    name: docker-ce
#    description: Docker repo
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#  when: ansible_os_family == 'CentOS'

- name: Add Docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker (Centos)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# if Amazon Linux
#- name: Install Docker (Amazon Linux)
#  shell: "amazon-linux-extras install docker -y"
#  when: ansible_distribution == 'Amazon'
# sudo amazon-linux-extras install docker
# sudo service docker start
# sudo usermod -a -G docker ec2-user

- name: Start and Enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes



